Adding dirty check, fixing a typo

diff --git a/script/release b/script/release
--- a/script/release
+++ b/script/release
@@ -26,8 +26,8 @@ echo "Releasing new version: ${NEW_VERSION}"
 #
 
 if [ "$BRANCH" != "master" ]; then
-  echo "Must release from master branch";
-  exit 1;
+  echo "Must release from master branch"
+  exit 1
 fi
 
 #
@@ -39,8 +39,8 @@ git remote show ${REMOTE} &> /dev/null
 rc=$?
 
 if [[ $rc != 0 ]]; then
-  echo "Remote \"${REMOTE}\" not found. Exiting.";
-  exit 1;
+  echo "Remote \"${REMOTE}\" not found. Exiting."
+  exit 1
 fi
 
 #
@@ -50,20 +50,30 @@ fi
 REMOTE_ACTUAL_URL=`git remote show release | grep Push | cut -d ":" -f2-`
 
 if [ $REMOTE_URL != $REMOTE_ACTUAL_URL ]; then
-  echo -e "Remote \"${REMOTE}\" PUSH url incorrect.\nShould be ${REMOTE_URL}. Exiting.";
-  exit 1;
+  echo -e "Remote \"${REMOTE}\" PUSH url incorrect.\nShould be ${REMOTE_URL}. Exiting."
+  exit 1
+fi
+
+#
+# Confirm our workspace is clean
+#
+
+WORKSPACE_STATUS=`git diff --exit-code`
+if [ $? != 0 ]; then
+  echo "Workspace is not clean. Exiting"
+  exit 2
 fi
 
 #
 # Ensure we're in sync with release remote
 #
 
-git fetch remote
-SYNC_STATUS=`git rev-list master...release/master`
+git fetch $REMOTE
+SYNC_STATUS=`git rev-list master...${REMOTE}/master`
 
 if [ -z "$SYNC_STATUS" ]; then
-  echo "Master is not in sync with release remote. Exiting.;
-  exit 1;
+  echo "Master is not in sync with release remote. Exiting.
+  exit 1
 fi
 
 #
